mobile: more spanish
daimo-eth/daimo pull request #1237
Opened 2024-07-27 10:28 UTC by dcposch

<img width="250" alt="Screenshot 2024-07-27 at 02 23 52" src="https://github.com/user-attachments/assets/d3378b21-adce-45dd-a3ca-140bd6c218f5">
<img width="250" alt="Screenshot 2024-07-27 at 02 23 58" src="https://github.com/user-attachments/assets/e23e7f75-4e22-4391-88c9-fc9f2808cd54">
<img width="250" alt="Screenshot 2024-07-27 at 02 24 01" src="https://github.com/user-attachments/assets/bd57faa2-601e-4b04-a336-8bcf23a59363">
<img width="250" alt="Screenshot 2024-07-27 at 02 24 09" src="https://github.com/user-attachments/assets/29d87cfb-32c4-4f65-90fe-1e3f309a81c3">
<img width="250" alt="Screenshot 2024-07-27 at 02 24 21" src="https://github.com/user-attachments/assets/f50b055a-ea63-42f0-8ff8-94f2f2f60949">
<img width="250" alt="Screenshot 2024-07-27 at 02 24 36" src="https://github.com/user-attachments/assets/bc255129-3b3d-444b-a7cd-852a05502d81">
<img width="250" alt="Screenshot 2024-07-27 at 02 26 13" src="https://github.com/user-attachments/assets/a302bc84-7315-4b49-9196-113bbfcc6b85">
<img width="250" alt="Screenshot 2024-07-27 at 02 27 14" src="https://github.com/user-attachments/assets/c7e0c152-3936-4495-b170-14001e518c16">
<img width="250" alt="Screenshot 2024-07-27 at 02 37 08" src="https://github.com/user-attachments/assets/be3248e3-0956-4c4c-a62c-2da3ddd02013">
<img width="250" alt="Screenshot 2024-07-27 at 02 37 14" src="https://github.com/user-attachments/assets/de5f5a16-f554-4909-9351-19ed956fff8a">
<img width="250" alt="Screenshot 2024-07-27 at 02 37 23" src="https://github.com/user-attachments/assets/8934cb46-3b0b-4b07-a8d0-0237280c0b56">
<img width="250" alt="Screenshot 2024-07-27 at 02 37 27" src="https://github.com/user-attachments/assets/b650f105-a78c-4cde-b0e1-38aa051d096b">
<img width="250" alt="Screenshot 2024-07-27 at 02 37 30" src="https://github.com/user-attachments/assets/3d8ad25e-5d47-4783-b792-8057f712a962">
<img width="250" alt="Screenshot 2024-07-27 at 02 37 38" src="https://github.com/user-attachments/assets/cbf67940-063d-465c-b640-c4827405d475">
<img width="250" alt="Screenshot 2024-07-27 at 02 37 48" src="https://github.com/user-attachments/assets/daa48d14-a2bf-4686-8747-b98bda123e0e">
<img width="250" alt="Screenshot 2024-07-27 at 02 38 06" src="https://github.com/user-attachments/assets/10899ad0-920e-41c8-a7bc-c1a6616f00f7">
<img width="250" alt="Screenshot 2024-07-27 at 02 38 27" src="https://github.com/user-attachments/assets/0421f0b2-43d3-42cf-807f-6c0d8c06b6a0">
<img width="250" alt="Screenshot 2024-07-27 at 02 38 40" src="https://github.com/user-attachments/assets/8b08943b-a541-4a19-b934-9d5f9c52614f">
<img width="250" alt="Screenshot 2024-07-27 at 02 38 45" src="https://github.com/user-attachments/assets/642705a6-2ba3-4b9a-b1ac-1d919f6331c4">
<img width="250" alt="Screenshot 2024-07-27 at 02 38 51" src="https://github.com/user-attachments/assets/01a54b00-ae2e-4375-92ef-11e91f82cfed">
<img width="250" alt="Screenshot 2024-07-27 at 02 43 23" src="https://github.com/user-attachments/assets/5e1e3008-f7c7-4c03-9620-97657d9fd248">
<img width="250" alt="Screenshot 2024-07-27 at 02 43 41" src="https://github.com/user-attachments/assets/37889a3a-f8e9-4114-9424-5c7213715816">
<img width="250" alt="Screenshot 2024-07-27 at 02 43 54" src="https://github.com/user-attachments/assets/345d9fd4-1d6b-41fe-b320-0dea79f2ca59">
<img width="250" alt="Screenshot 2024-07-27 at 02 43 57" src="https://github.com/user-attachments/assets/459507ab-e918-4350-952f-317846238534">
<img width="250" alt="Screenshot 2024-07-27 at 02 44 04" src="https://github.com/user-attachments/assets/91b2927e-4851-436a-92de-7e7c35f61094">
<img width="250" alt="Screenshot 2024-07-27 at 02 44 15" src="https://github.com/user-attachments/assets/bbe8797a-5f8b-4fa9-a861-1cf0165a40d8">
<img width="250" alt="Screenshot 2024-07-27 at 02 48 05" src="https://github.com/user-attachments/assets/ac701e40-eb10-481e-b0ba-19815b4b6be3">
<img width="250" alt="Screenshot 2024-07-27 at 02 53 08" src="https://github.com/user-attachments/assets/287c72d4-e3c2-48d8-b042-413fc13ebb32">
<img width="250" alt="Screenshot 2024-07-27 at 02 53 32" src="https://github.com/user-attachments/assets/30ea5d36-edd6-43d7-a82a-3c948a183cda">
<img width="250" alt="Screenshot 2024-07-27 at 02 54 20" src="https://github.com/user-attachments/assets/97dbb738-7c53-4fe0-b5b7-8509e0dca7b8">
<img width="250" alt="Screenshot 2024-07-27 at 02 54 31" src="https://github.com/user-attachments/assets/e4826a0a-e20b-47c0-af57-1868cabb7770">
<img width="250" alt="Screenshot 2024-07-27 at 03 10 03" src="https://github.com/user-attachments/assets/91fb142c-ed08-47d1-b8cd-061287846123">
<img width="250" alt="Screenshot 2024-07-27 at 03 10 05" src="https://github.com/user-attachments/assets/2ae1ab2e-5d9b-48c0-bc8c-b98569dbedf6">
<img width="250" alt="Screenshot 2024-07-27 at 03 14 28" src="https://github.com/user-attachments/assets/a03c2e68-df13-4cc7-97e9-8e8441acbbd0">

2024-07-27 10:43 UTC, Ethanol48 commented
I'm seeing some strings that are a bit strange, I'll have a look this afternoon.

2024-07-27 10:44 UTC, Ethanol48 commented
I'll create a PR for simplicity

2024-07-27 13:48 UTC, Ethanol48 commented
I found some strings that need to be exported to i18n

2024-07-27 13:52 UTC, Ethanol48 commented
I found another bug, in the simulator, in the `Deposit` tab the line for deposits doesn't seem to follow the translation, I've check the `es.ts` file and is not a typo, 

For Withdraw this doesn't happen, it works fine, I have look through the code, but I couldn't find the source.

attaching a screenshot for showcase:

<img width="371" alt="Screenshot 2024-07-27 at 14 46 06" src="https://github.com/user-attachments/assets/b25cf5b9-da20-43f8-938c-daf824e8cb9a">

2024-07-27 13:55 UTC, Ethanol48 commented
I also encountered some hardcoded text in some titles of Modals imported to `DepositScreen.tsx`, found inside the `sheet` folder. I'm not sure if this text is critical for functionality, I wanted to point it out.

2024-07-27 14:12 UTC, Ethanol48 commented
I found a bug, seems to be from the package "daimo-common", it returns the english translation when it should be the spanish, I've check and the translation is spanish is set correctly.

<img width="374" alt="Screenshot 2024-07-27 at 15 08 16" src="https://github.com/user-attachments/assets/bdb0aac2-bb7b-4312-aece-9f7d46b5c304">

it should be `hace {time}`

2024-07-27 19:00 UTC, Ethanol48 requested changes
Mostly refactoring for i18n

2024-07-27 19:00 UTC, Ethanol48 commented on apps/daimo-mobile/src/view/shared/SearchResults.tsx
In line 93 of this file, there's some texts that need to be refactored for i18n

2024-07-27 19:01 UTC, Ethanol48 commented
Sorry about the request changes, I'm using my phone and the interface isn't the greatest in the app, there are some requests that are duplicated.

2024-07-27 21:54 UTC, Ethanol48 commented
Added some fields in i18n and implemented them where it was needed, made some final touches to the spanish translations, it should be good to go for the daimo-mobile part.

I'm still having some issues from "daimo-common" that is giving the english translation when it should be the spanish.

This been resolved, it should be good to go.

2024-07-28 01:16 UTC, dcposch commented
@Ethanol48 your updates look great, thanks!

2024-07-28 01:16 UTC, merged