Move HistoryOp inside bottom sheet
daimo-eth/daimo pull request #494
Opened 2023-12-04 16:13 UTC by wojtus7

Move HistoryOp screen inside bottom heet on home screen

iOS:

https://github.com/daimo-eth/daimo/assets/42337257/0af12407-31ca-45d6-8aac-507f49cdb23f

android:

https://github.com/daimo-eth/daimo/assets/42337257/75cec4a6-f6eb-40f3-86f9-7fbf02f3d9d0

2023-12-04 20:58 UTC, dcposch approved these changes
LGTM, left a question

2023-12-04 20:58 UTC, dcposch commented on apps/daimo-mobile/src/view/screen/HomeScreen.tsx
> +              <Spacer h={screenDimensions.height > 680 ? 64 : 24} />
which device needs the smaller spacer?

2023-12-05 17:17 UTC, wojtus7 commented on apps/daimo-mobile/src/view/screen/HomeScreen.tsx
> +              <Spacer h={screenDimensions.height > 680 ? 64 : 24} />
My iPhone SE 😖

2024-01-17 22:38 UTC, nalinbhardwaj commented
- Remove offline bar on transfer screen:

<img width="256" src="https://github.com/daimo-eth/daimo/assets/6984346/2609a830-960f-46e2-8283-813e7ccedfbe">

- Seems like header image related code might have a bug? I get a blank space at the top and the bottom cuts off:

<img width="256" src="https://github.com/daimo-eth/daimo/assets/6984346/4c6dffd4-303c-4b0d-b0ad-1cf897d29e1b">

- Pulling up the sheet from the transfer screen also seems bugged. Doesn't pull up at all in the flow default click > pull up:

https://github.com/daimo-eth/daimo/assets/6984346/3e9d3ff0-a564-410c-9d62-a6ba71c69098

- nit: payment link bubble leads to the same page as its transfer currently, can disable tap target for those rows.

- Console warning: Sending  `onAnimatedValueUpdate` with no listeners registered.

- Make sure the interactions work well in pairing with https://github.com/daimo-eth/daimo/pull/610, needs rebase over that.

2024-01-17 22:39 UTC, nalinbhardwaj requested changes
see comment, would appreciate if you could test it on a real device as well and make sure it doesn't feel jank in any interactions.

2024-01-19 17:36 UTC, wojtus7 commented
@nalinbhardwaj I think I resolved all things except:
"Console warning: Sending  onAnimatedValueUpdate with no listeners registered."
But I think this happened also before changes in this PR (?) so I would handle it separately because it can be totally not connected with implemented functionality, but I will surely take a look at it asap

Wanted to let you know but I still need to test it a little more on physical devices to make sure sure everything works smoothly 👌

2024-01-20 12:24 UTC, dcposch commented
Rebased on master. (Had to replay using `git diff --patch` due to merge commits.)

Fixed one more issue: when you open a transaction, then swipe down to minimize the bottomsheet again, the transaction didn't go away:
<img width="422" alt="Screenshot 2024-01-20 at 03 51 35" src="https://github.com/daimo-eth/daimo/assets/169280/ebdd9f01-b5eb-4a2a-8901-025326e37dd0">

Fixed. Swipe down now returns you to the home HistoryOpList.

2024-01-21 07:30 UTC, nalinbhardwaj approved these changes
lgtm

2024-01-21 07:30 UTC, merged